version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  db:
    image: mongo:4
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  api:
    build: .
    restart: on-failure
    depends_on:
      - db
      - redis
    volumes:
      - ./:/usr/src/app:cached
      - npm_cache:/root/.npm:delegated
      - node_modules:/app/node_modules:delegated
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
      REDIS_PORT: ${REDIS_PORT}
      NODE_ENV: ${NODE_ENV}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

volumes:
  redis_data:
    driver: local
  mongodb:
  npm_cache:
  node_modules:
